<!DOCTYPE html>
<html lang="en">   
<!-------------------Head INCLUDE here------------------------------->
<?php include '/XAMPP/htdocs/WebApplication/Assets/Files/header.php';?>
<!------------------------------------------------------------------->

<!-------------------body START here--------------------------------------------->
<body>
<!-------------------NAVBAR INCLUDE here------------------------------->
<?php include '/XAMPP/htdocs/WebApplication/Assets/Files/navbar.php';?>
<div class="content12">
    <h4 >Growing Older with HIV</h4>
    <p class="content26">At the start of the epidemic more than 30 years ago, people who were diagnosed with HIV or AIDS could expect to live only 1-2 years after that diagnosis. This meant that the issues of aging were not a major focus for people with HIV disease.But today, thanks to improvements in the effectiveness of treatment with HIV medicine (called antiretroviral therapy or ART), people with HIV who are diagnosed early in their infection, and who get and stay on ART can keep the virus suppressed and live long and healthy lives. For this reason, nearly half of people living with diagnosed HIV in the United States are aged 50 and older. Many of them have been living with HIV for years; others are recently infected or diagnosed.According to the Centers for Disease Control and Prevention (PDF, 3.1 MB) (CDC), of the estimated 1.1 million people with HIV in the U.S. in 2018, approximately 400,000 (36%) were aged 55 and older. In addition, people aged 50 and older accounted for 17% of the 37,968 new HIV diagnoses in 2018 in the United States and 6 dependent areas.Older adults (those over age 50) with HIV make up 46% of the half a million clients served by the Ryan White HIV/AIDS Program (RWHAP). In 2018, 92% of clients aged 50 and older receiving RWHAP HIV medical care were virally suppressed, which was higher than the national RWHAP average (87%). (Learn more about the RWHAP and older adults.</p>
    <h4> Emergencies and Disasters and HIV</h4>
    <p class="content26">To stay healthy, people with HIV must take their HIV medication every day, exactly as prescribed. A natural disaster or other emergency may make it harder for you to do this. To avoid interruptions in your HIV treatment, store a 7- to 10-day supply in a waterproof container to take with you if you have to evacuate. Talk to your provider or your pharmacist to find out if a 30- or 90-day refill of your HIV medicine is recommended or available in an emergency, or if you can receive your medicine by mail.</p>
    <h4>Employment and Health</h4>
    <p class="content26">With proper care and treatment, many people living with HIV lead normal, healthy lives, including having a job. Most people living with HIV can continue working at their current jobs or look for a new job in their chosen field. Your overall well-being and financial health can be more stable when you are gainfully employed.</p>
    <h4>Exercise and Physical Activity</h4>
    <p class="content26">Being HIV-positive is no different from being HIV-negative when it comes to exercise. Regular physical activity and exercise are part of a healthy lifestyle for everyone, including people living with HIV.According to the evidence-based Physical Activity Guidelines (2018), adults need at least 150 to 300 minutes per week of moderate-intensity aerobic activity, like biking, brisk walking, or fast dancing. Adults also need muscle-strengthening activity, like lifting weights or doing push-ups, at least 2 days per week.</p>
    <h4> Food Safety and Nutrition</h4>
    <p class="content26">Good nutrition is important to all people—whether or not they are living with HIV. But some conditions related to treating HIV or AIDS (including wasting, diarrhea, and lipid abnormalities) mean that proper nutrition is really important to people with HIV. Eating well is key to maintaining strength, energy, and a healthy immune system. In addition, because HIV can lead to immune suppression, food safety and proper hygiene are concerns when it comes to preventing infections.For more information, see the Department of Veterans Affairs’ HIV/AIDS: Diet and Nutrition A healthy diet is essential to maintaining good health across your lifespan. The U.S. Food and Drug Administration (FDA) defines a healthy diet as one that: provides enough of each essential nutrient; contains a variety of foods from all of the basic food groups; provides adequate energy to maintain a healthy weight; and does not contain excess fat, sugar, salt, or alcohol. </p>
    <h4>Housing and Health</h4>
    <p class="content26">Stable housing is closely linked to successful HIV outcomes. With safe, decent, and affordable housing, people with HIV are better able to access medical care and supportive services, get on HIV treatment, take their HIV medication consistently, and see their health care provider regularly. In short: the more stable your living situation, the better you do in care.Individuals with HIV who are homeless or lack stable housing, on the other hand, are more likely to delay HIV care and less likely to access care consistently or to adhere to their HIV treatment.Throughout many communities, people with HIV risk losing their housing due to such factors as stigma and discrimination, increased medical costs and limited incomes or reduced ability to keep working due to HIV-related illnesses.In addition to the HOPWA program, people living with HIV are eligible for any HUD program for which they might otherwise qualify (such as by being low-income or homeless). Programs include public housing, the Section 8 Housing Choice Voucher Program, housing opportunities supported by Community Development Block Grants, the HOME Investment Partnerships Program, and the Continuum of Care Homeless Assistance Program.</p>
    <h4>Traveling Outside</h4>
    <p class="content26">With proper treatment, people with HIV can lead healthy and active lives, including traveling for business and pleasure. However, traveling to other countries, particularly developing countries, may require some advance preparation and special precautions.With proper treatment, people with HIV can lead healthy and active lives, including traveling for business and pleasure. However, traveling to other countries, particularly developing countries, may require some advance preparation and special precautions.Some countries restrict visitors with HIV from entering their borders or staying for long periods of time. Others permit discrimination on the basis of sexual orientation or gender identification. According to the State Department, more than 70 countries consider consensual same-sex relations a crime, sometimes carrying severe punishment. Before you travel internationally, be aware of the laws, policies, and practices in the country or countries you plan to visit. This information is usually available from the consular offices of each country or in the State Department’s country information summaries, along with information about entry and exit requirements.</p>



</div>

<?php include '/XAMPP/htdocs/WebApplication/Assets/Files/top.php';?>
<!-------------------FOOTER INCLUDE here------------------------------->
<?php include '/XAMPP/htdocs/WebApplication/Assets/Files/footer.php';?> 
</body>
<!-------------------body END here----------------------------------------------->
</html>